config/routes.rb
Rails.application.routes.draw do
  root 'axes#index'
  devise_for :users, class_name: 'FormUser', 
        :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  resources :axes do
    post 'toggle_like'
  end
  get 'users/:id/rig' => 'axes#rig', as: 'user_rig'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Guitar Rigs</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Guitar Rigs", root_path, class:"navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <p class="navbar-text">Yo <%=current_user.username %> \m/</p>
              <li><%= link_to "My Rig", user_rig_path(current_user.id) %></li>
              <li><%= link_to new_axe_path do %>
                  <span class="glyphicon glyphicon-plus"></span>&nbsp;New Axe
                <% end %>
              </li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Log In", new_user_session_path %></li>  
              <li><%= link_to "Sign Up", new_user_registration_path %></li>  
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </div> <!-- /.container -->
  </nav>
  <div class="container">
    <% flash.each do |name,msg| %>
      <%= content_tag(:div,msg,class: "alert alert-info") %>
    <%end %>
    <%= yield %>
  </div>

</body>
</html>